[package]
name = "bingohost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.148", features = ["serde_derive"] }
serde_json = "1.0.89"
serde_repr = "0.1.9"
tokio = { version = "1.22.0", features = ["net", "io-util", "rt", "macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
